name: Build FakeSMTP

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permet de déclencher manuellement l'action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Changez cette version si une autre est nécessaire
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fakeSMTP
          path: target/fakeSMTP-*.jar
